version: 2
jobs:
  node18:
    working_directory: ~/mern-starter # directory where steps will run
    docker:
      - image: circleci/node:18.18
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
  node20:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:20.9
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  workflow-1:
    jobs:
      - node18
      - node20
